### ISSUE TITLE
get_p in gridop

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#10]
I added a version of get_p in gridop. What is implemented is a "finite volume" implementation, where the density is integrated level-wise (assuming rho is constant in a given sigma rho-layer) from the surface. i.e. it is strictly equivalent to cumsum on w-levels. This is probably not what is actually implemented in croco, but it gives something satisfying.

Please check that it looks fine (and that it works if you want, but I am currently using it so...) and delete the old version get_p_old if it is OK

**Comment by apatlpo** [comment]
no time to check but I trust you

n'ai pas peur d'effacer, en fait rien n'est vraiment effacé pour de bon avec git ;)
