### ISSUE TITLE
list of changes / improvements

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#20]
**General:**

- [ ] change name `g_default`(e.g. to `grav`). If we are to change this name, we should make sure the modification is also made in gridop and vmodes

**In vmodes:**
 - [x] method for saving and loading modes

**Comment by apatlpo** [comment]
The first item seems like an easy one to do.
Let's agree on one choice and I'll propagate the modifications.

My choice goes for `grav`

**Comment by NoeLahaye** [comment]
+1 for grav

**Comment by apatlpo** [comment]
3ef5cbf should take care of the `grav` treatment.

`grav` is the name of the default parameter in  postp
Each method that needs it accepts an optional parameter called `g` that default to `grav`

I'm pretty brain dead this afternoon and this was a good activity.

let's close this for now
