### ISSUE TITLE
"overwrite" in postp.store_diagnostic does not do the job

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#23]
https://github.com/slgentil/croco/blob/34845403745088d963beadcab3bc507233249f99/crocosi/postp.py#L471

**Comment by apatlpo** [comment]
@NoeLahaye could you please tell me if d0b1b37 fixes this for you ?

**Comment by NoeLahaye** [comment]
YES, problem fixed, thanks @apatlpo
