### ISSUE TITLE
bug when chunking with zarr

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#27]
@apatlpo , would you mind fixing this (that should be easy for you)? 
I think that's a typo. When we specify `chunks` when calling  `postp.Run`, the corresponding dataset is `chunk`method... See this line, I guess:
https://github.com/slgentil/croco/blob/2b219c37cbc5893dc8b97f6ff2ea1c46a4574b2c/crocosi/postp.py#L232

**Comment by apatlpo** [comment]
oups ... good catch, thanks.
This is fixed starting from a2dbb2f

Don't forget temporal chunk key becomes `time` (and not `time_counter`) with zarr archives ...
