### ISSUE TITLE
update interp2z in gridop.py

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#6]
interp2z and interp2z_3d should be updated in gridop.py to be compatible with the fast_interp routine. The latter now includes nearest or linear extrapolation at the top and the bottom, and hence requires 2 more arguments (integers -- 5 args in total). I think the corrected versions are the one in proj_modes.ipynb (in tutorials). Aurélien did the modification of the fast_interp routine, can you confirm and make the changes accordingly?

**Comment by apatlpo** [comment]
Correct

Let's take this chance to update and improve interp2z (in proj_modes) (list may evolve along the way):

- [ ] add top/bottom extrap parameters  (align with notebook version)

- [ ] agree on API: number of dimensions allowed; core dimension treatment

- [ ] design test code for  interp2z

**Comment by apatlpo** [comment]
I have the feeling we could close this.

Would you agree?

@NoeLahaye 
@slgentil

**Comment by NoeLahaye** [comment]
Agree, I just updated taking the version in proj_modes.ipynb (the only difference is in the extrapolation parameters : fast_interp_3d now requires 2 parameters, for bottom and top)
