### ISSUE TITLE
minor error and suggestions for postp _adjust_grid

### ISSUE THREAD

**Issue by NoeLahaye** [slgentil/croco#9]
I think l. 321 should read "_f0, _beta = None, None" istead of "f0, beta = None, none"

Puisque f est présent dans le netCDF grid, pourquoi ne pas l'utiliser comme coordonnée ? Ca évite d'avoir à donner f0, beta s'ils ne sont pas dans les fichiers de sortie (ce ne sont que des attributs) et de faire potentiellement des erreurs. Par contre on perdrai f_u, f_v, mais ils se recalculent très facilement avec grid.interp

Si OK je ferai les modifs nécessaires et ferai un pull request

**Comment by apatlpo** [comment]
oui et oui je dirais

pour le deuxième point je n'avais pas réalisé que f était aussi dans le fichier grille

@slgentil qu'en penses-tu

**Comment by apatlpo** [comment]
issue resolved by 4662a273fd69634bbc59861483f6d8e8d2baabaa

thanks @NoeLahaye !
